[tool.poetry]
name = "docker-home"
version = "0.1.0"
description = ""
authors = ["assmylyaev <vape.store2016@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
